schema_version = "1.0.0"

id = "io_scene_owm"
version = "3.2.8"
name = "OWM Import"
tagline = "Import files from the Overwatch extraction tools (DataTool)"
maintainer = "overtools"
type = "add-on"
tags = ["Import-Export"]
website = "https://github.com/overtools/io_scene_owm"

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

[permissions]
files = "Importing files from disk"

[build]
paths_exclude_pattern = [
  "__pycache__/",
  "/.idea/",
  "/.vscode/",
  "/.git/",
  ".gitignore",
  ".gitattributes",
  "README.md",
  "build.bat",
  "/*.zip", # build outputs
]